### ISSUE TITLE
Can't really tap the bottom buttons on a Galaxy S21

### ISSUE THREAD

**Issue by kelvie** [bilgincoskun/brogue-android-port#10]
Not sure if it's the curved screen, but it seems really difficult to hit the bottom "Inventory" button on this phone, I have to constantly tap it to get the inventory to pop up (and it'll often disappear cause I've tapped too many times!)

Let me know what information you need to help debug this...

**Comment by kelvie** [comment]
OK, I think I may have figured it out, it's expecting a "swipe up" motion to activate those buttons, not an actual tap, right?

**Comment by bilgincoskun** [comment]
Sorry for the late answer. The app locks to the touched cell, so swiping and tapping is not different. Like you said, due to the curved screen, it may be calculating the first cell wrong. Unfortunately I am busy with other things right now, so it might take a while to properly investigate the root of the problem. In the mean time, you can try to change screen width and height to stay in non-curved space and  check if the issue still persists.

**Comment by kelvie** [comment]
Not a problem, it turns out I don't really enjoy playing on a phone anyway. Thanks for the reply!

**Comment by bilgincoskun** [comment]
I see,no worries. I am closing the issue for now since there is no way to debug currently. Feel free to comment if you start playing on phone again and I'll reopen the issue.

**Comment by dmitry-kulak** [comment]
I have the same issue on Pixel 4a. The game is practically unplayable.

**Comment by bilgincoskun** [comment]
Does this happen only in the latest version, or it was a problem in previous versions also? 
Another thing is if only tapping the bottom is problematic and not other areas, it might be due to the soft keys. If so you can try to resize the screen manually from the settings.

**Comment by dmitry-kulak** [comment]
Both in previous and current versions.
Screen resize did the trick, it seems.

**Comment by bilgincoskun** [comment]
Good to hear. Some devices with soft keys seems to have this problem but I am not sure why. I might need to investigate this further in the future.
